const allConditions = {
  1: {
    id: 1,
    nameEU: "Mint",
    nameUS: null,
    isEU: true,
    isUS: false,
    shortname: "M",
    shortnameUS: null,
  },
  2: {
    id: 2,
    nameEU: "Near-Mint",
    nameUS: "Near-Mint",
    isEU: true,
    isUS: true,
    shortname: "NM",
    shortnameUS: "NM",
  },
  3: {
    id: 3,
    nameEU: "Excellent",
    nameUS: "Slightly Played",
    isEU: true,
    isUS: false,
    shortname: "EXC",
    shortnameUS: "LP",
  },
  4: {
    id: 4,
    nameEU: "Good",
    nameUS: "Moderately Played",
    isEU: true,
    isUS: true,
    shortname: "GD",
    shortnameUS: "MP",
  },
  5: {
    id: 5,
    nameEU: "Light-Played",
    nameUS: null,
    isEU: true,
    isUS: false,
    shortname: "LP",
    shortnameUS: null,
  },
  6: {
    id: 6,
    nameEU: "Played",
    nameUS: "Heavily Played",
    isEU: true,
    isUS: true,
    shortname: "PL",
    shortnameUS: "HP",
  },
  7: {
    id: 7,
    nameEU: "Poor",
    nameUS: "Damaged",
    isEU: true,
    isUS: true,
    shortname: "PO",
    shortnameUS: "D",
  },
};

export default {
  allConditions,
};
